services:
  db:
    image: postgres:16-alpine
    container_name: dotnet_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EventTicketDb
    ports:
      - "5432:5432"
    # volumes:
    #   - ./infra/postgres/data:/var/lib/postgresql/data
    #   - ./infra/postgres/backups:/backups
    #   - ./infra/postgres/scripts/restore-latest.sh:/docker-entrypoint-initdb.d/restore-latest.sh:ro
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: dotnet_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: dotnet_api
    depends_on:
      - db
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=EventTicketDb;Username=postgres;Password=postgres
      - RabbitMQ__Host=rabbitmq
    ports:
      - "5273:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge