services:
  db:
    image: postgres:16-alpine
    container_name: dotnet_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      
      - ./infra/postgres/data:/var/lib/postgresql/data
      
      - ./infra/postgres/backups:/backups
      
      - ./infra/postgres/scripts/restore-latest.sh:/docker-entrypoint-initdb.d/restore-latest.sh:ro
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: dotnet_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - app-network

  backend:
    build:
      # Вказуємо точний шлях до папки, де лежить твій .csproj
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: dotnet_api
    depends_on:
          db:
            condition: service_started
          rabbitmq:
            condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - RabbitMQ__Host=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    ports:
      - "${BACKEND_PORT}:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge